remote_theme: pages-themes/cayman@v0.2.0
title: Test
description: des
darkmode: true
hide_first_title: true
logo_url: https://github.com/curiouswalk/manim/assets/157306209/a20ef04c-9e8c-422f-97a7-27f78599dcd8
